In [54]:
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
import pandas as pd

In [77]:
df = pd.read_csv('CarPrice.csv')
df

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [56]:
name = df['CarName'].unique()

In [57]:
del df['car_ID']

In [58]:
df['aspiration'].unique()

array(['std', 'turbo'], dtype=object)

In [78]:
df['fueltype'].unique()

array(['gas', 'diesel'], dtype=object)

In [94]:
#data preprocessing 
#spliting car name and taking only the brand name 
brand = df['CarName'].apply(lambda x: x.split(' ')[0])
df.insert(1,"Brand",brand)
del df['CarName']

In [95]:
df['Brand'].values

array(['alfa-romero', 'alfa-romero', 'alfa-romero', 'audi', 'audi',
       'audi', 'audi', 'audi', 'audi', 'audi', 'bmw', 'bmw', 'bmw', 'bmw',
       'bmw', 'bmw', 'bmw', 'bmw', 'chevrolet', 'chevrolet', 'chevrolet',
       'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge',
       'dodge', 'dodge', 'honda', 'honda', 'honda', 'honda', 'honda',
       'honda', 'honda', 'honda', 'honda', 'honda', 'honda', 'honda',
       'honda', 'isuzu', 'isuzu', 'isuzu', 'isuzu', 'jaguar', 'jaguar',
       'jaguar', 'maxda', 'maxda', 'mazda', 'mazda', 'mazda', 'mazda',
       'mazda', 'mazda', 'mazda', 'mazda', 'mazda', 'mazda', 'mazda',
       'mazda', 'mazda', 'mazda', 'mazda', 'buick', 'buick', 'buick',
       'buick', 'buick', 'buick', 'buick', 'buick', 'mercury',
       'mitsubishi', 'mitsubishi', 'mitsubishi', 'mitsubishi',
       'mitsubishi', 'mitsubishi', 'mitsubishi', 'mitsubishi',
       'mitsubishi', 'mitsubishi', 'mitsubishi', 'mitsubishi',
       'mitsubishi', 'Nissan', 'nissan', 'nissan', 'nissan', 'nissan',
       'nissan', 'nissan', 'nissan', 'nissan', 'nissan', 'nissan',
       'nissan', 'nissan', 'nissan', 'nissan', 'nissan', 'nissan',
       'nissan', 'peugeot', 'peugeot', 'peugeot', 'peugeot', 'peugeot',
       'peugeot', 'peugeot', 'peugeot', 'peugeot', 'peugeot', 'peugeot',
       'plymouth', 'plymouth', 'plymouth', 'plymouth', 'plymouth',
       'plymouth', 'plymouth', 'porsche', 'porcshce', 'porsche',
       'porsche', 'porsche', 'renault', 'renault', 'saab', 'saab', 'saab',
       'saab', 'saab', 'saab', 'subaru', 'subaru', 'subaru', 'subaru',
       'subaru', 'subaru', 'subaru', 'subaru', 'subaru', 'subaru',
       'subaru', 'subaru', 'toyota', 'toyota', 'toyota', 'toyota',
       'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota',
       'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota',
       'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota',
       'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota',
       'toyota', 'toyota', 'toyota', 'toyouta', 'vokswagen', 'volkswagen',
       'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen',
       'volkswagen', 'vw', 'vw', 'volkswagen', 'volkswagen', 'volkswagen',
       'volvo', 'volvo', 'volvo', 'volvo', 'volvo', 'volvo', 'volvo',
       'volvo', 'volvo', 'volvo', 'volvo'], dtype=object)

In [96]:
#changing the brand name 
def replace_name(a,b, columnName):
  df[columnName].replace(a, b, inplace=True)
replace_name(('vw', 'vokswagen'), 'volkswagen', 'Brand')
replace_name('maxda','mazda','Brand')
replace_name('toyouta','toyota','Brand')

In [97]:
df['Brand'].values
df

,symboling,Brand,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,3,alfa-romero,1,0,1,0,2,0,88.6,168.8,...,130,5,3.47,2.68,9.0,111,5000,21,27,13495.0
1,3,alfa-romero,1,0,1,0,2,0,88.6,168.8,...,130,5,3.47,2.68,9.0,111,5000,21,27,16500.0
2,1,alfa-romero,1,0,1,2,2,0,94.5,171.2,...,152,5,2.68,3.47,9.0,154,5000,19,26,16500.0
3,2,audi,1,0,0,3,1,0,99.8,176.6,...,109,5,3.19,3.40,10.0,102,5500,24,30,13950.0
4,2,audi,1,0,0,3,0,0,99.4,176.6,...,136,5,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,volvo,1,0,0,3,2,0,109.1,188.8,...,141,5,3.78,3.15,9.5,114,5400,23,28,16845.0
201,-1,volvo,1,1,0,3,2,0,109.1,188.8,...,141,5,3.78,3.15,8.7,160,5300,19,25,19045.0
202,-1,volvo,1,0,0,3,2,0,109.1,188.8,...,173,5,3.58,2.87,8.8,134,5500,18,23,21485.0
203,-1,volvo,0,1,0,3,2,0,109.1,188.8,...,145,3,3.01,3.40,23.0,106,4800,26,27,22470.0
204,-1,volvo,1,1,0,3,2,0,109.1,188.8,...,141,5,3.78,3.15,9.5,114,5400,19,25,22625.0

In [98]:
#changing the brand values to lower case
df['Brand'] = df['Brand'].str.lower()

In [99]:
df['Brand'].values

array(['alfa-romero', 'alfa-romero', 'alfa-romero', 'audi', 'audi',
       'audi', 'audi', 'audi', 'audi', 'audi', 'bmw', 'bmw', 'bmw', 'bmw',
       'bmw', 'bmw', 'bmw', 'bmw', 'chevrolet', 'chevrolet', 'chevrolet',
       'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge', 'dodge',
       'dodge', 'dodge', 'honda', 'honda', 'honda', 'honda', 'honda',
       'honda', 'honda', 'honda', 'honda', 'honda', 'honda', 'honda',
       'honda', 'isuzu', 'isuzu', 'isuzu', 'isuzu', 'jaguar', 'jaguar',
       'jaguar', 'mazda', 'mazda', 'mazda', 'mazda', 'mazda', 'mazda',
       'mazda', 'mazda', 'mazda', 'mazda', 'mazda', 'mazda', 'mazda',
       'mazda', 'mazda', 'mazda', 'mazda', 'buick', 'buick', 'buick',
       'buick', 'buick', 'buick', 'buick', 'buick', 'mercury',
       'mitsubishi', 'mitsubishi', 'mitsubishi', 'mitsubishi',
       'mitsubishi', 'mitsubishi', 'mitsubishi', 'mitsubishi',
       'mitsubishi', 'mitsubishi', 'mitsubishi', 'mitsubishi',
       'mitsubishi', 'nissan', 'nissan', 'nissan', 'nissan', 'nissan',
       'nissan', 'nissan', 'nissan', 'nissan', 'nissan', 'nissan',
       'nissan', 'nissan', 'nissan', 'nissan', 'nissan', 'nissan',
       'nissan', 'peugeot', 'peugeot', 'peugeot', 'peugeot', 'peugeot',
       'peugeot', 'peugeot', 'peugeot', 'peugeot', 'peugeot', 'peugeot',
       'plymouth', 'plymouth', 'plymouth', 'plymouth', 'plymouth',
       'plymouth', 'plymouth', 'porsche', 'porcshce', 'porsche',
       'porsche', 'porsche', 'renault', 'renault', 'saab', 'saab', 'saab',
       'saab', 'saab', 'saab', 'subaru', 'subaru', 'subaru', 'subaru',
       'subaru', 'subaru', 'subaru', 'subaru', 'subaru', 'subaru',
       'subaru', 'subaru', 'toyota', 'toyota', 'toyota', 'toyota',
       'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota',
       'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota',
       'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota',
       'toyota', 'toyota', 'toyota', 'toyota', 'toyota', 'toyota',
       'toyota', 'toyota', 'toyota', 'toyota', 'volkswagen', 'volkswagen',
       'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen',
       'volkswagen', 'volkswagen', 'volkswagen', 'volkswagen',
       'volkswagen', 'volkswagen', 'volvo', 'volvo', 'volvo', 'volvo',
       'volvo', 'volvo', 'volvo', 'volvo', 'volvo', 'volvo', 'volvo'],
      dtype=object)

In [100]:
#Label encoding 
def label_encoding(colname):
    df[colname] = df[colname].astype('category')
    return(df[colname].cat.codes)
df['fueltype'] = label_encoding('fueltype')
#numeric conversion is done alphabetically i.e. diesel = 0, and gas = 1

#encoding for aspiration 
df['aspiration'] = label_encoding('aspiration')

#encoding for doornumber 
df['doornumber'] = label_encoding('doornumber')


#encoding for carbody
df['carbody'] = label_encoding('carbody')

#encoding for drivewheel 
df['drivewheel'] = label_encoding('drivewheel')

#encoding for engine location 
df['enginelocation'] = label_encoding('enginelocation')

#encoding for  engine type 
df['enginetype'] = label_encoding('enginetype')

#encoding for cylindernumber 
df['cylindernumber'] = label_encoding('cylindernumber')

#encoding for fuelsystem
df['fuelsystem'] = label_encoding('fuelsystem')

In [113]:

df.describe()

,symboling,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,...,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,0.834146,0.902439,0.180488,0.439024,2.614634,1.326829,0.014634,98.756585,174.049268,65.907805,...,126.907317,3.253659,3.329756,3.255415,10.142537,104.117073,5125.121951,25.219512,30.751220,13276.710571
std,1.245307,0.297446,0.385535,0.497483,0.859081,0.556171,0.120377,6.021776,12.337289,2.145204,...,41.642693,2.013204,0.270844,0.313597,3.972040,39.544167,476.985643,6.542142,6.886443,7988.852332
min,-2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,86.600000,141.100000,60.300000,...,61.000000,0.000000,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000
25%,0.000000,1.000000,0.000000,0.000000,2.000000,1.000000,0.000000,94.500000,166.300000,64.100000,...,97.000000,1.000000,3.150000,3.110000,8.600000,70.000000,4800.000000,19.000000,25.000000,7788.000000
50%,1.000000,1.000000,0.000000,0.000000,3.000000,1.000000,0.000000,97.000000,173.200000,65.500000,...,120.000000,5.000000,3.310000,3.290000,9.000000,95.000000,5200.000000,24.000000,30.000000,10295.000000
75%,2.000000,1.000000,0.000000,1.000000,3.000000,2.000000,0.000000,102.400000,183.100000,66.900000,...,141.000000,5.000000,3.580000,3.410000,9.400000,116.000000,5500.000000,30.000000,34.000000,16503.000000
max,3.000000,1.000000,1.000000,1.000000,4.000000,2.000000,1.000000,120.900000,208.100000,72.300000,...,326.000000,7.000000,3.940000,4.170000,23.000000,288.000000,6600.000000,49.000000,54.000000,45400.000000

### Data Normalization

In [140]:
df_normalized = (df-df.mean())/(df.max()-df.min())

#assigning the features to variable X after normalizing it 

X = df_normalized[['symboling','fueltype','aspiration','doornumber','carbody',
                    'drivewheel','enginelocation','wheelbase','carlength',
             'carwidth','curbweight','enginetype','cylindernumber', 'enginesize',
            'fuelsystem','boreratio', 'stroke', 'compressionratio',
            'horsepower', 'peakrpm', 'citympg', 'highwaympg'
            ]]

#assigning the price tho variable Y after normalizing it

y = df_normalized['price']

### Splitting Data

In [141]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8 ,test_size = 0.2, random_state=3)

In [143]:
X_train

,symboling,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,...,cylindernumber,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg
135,0.233171,0.097561,-0.180488,-0.439024,0.096341,-0.163415,-0.014634,0.010012,0.187324,0.049350,...,-0.019512,-0.022292,0.249477,0.150174,-0.088293,-0.052659,0.024512,0.050971,-0.117209,-0.072401
134,0.433171,0.097561,-0.180488,0.560976,-0.153659,-0.163415,-0.014634,0.010012,0.187324,0.049350,...,-0.019512,-0.022292,0.249477,-0.564111,-0.564483,-0.052659,0.024512,0.050971,-0.117209,-0.072401
41,-0.166829,0.097561,-0.180488,-0.439024,0.096341,-0.163415,-0.014634,-0.065790,0.020160,-0.058984,...,-0.019512,-0.063801,0.249477,-0.128397,0.154564,-0.071409,-0.012988,0.275460,-0.033875,-0.072401
161,-0.166829,0.097561,-0.180488,-0.439024,-0.153659,-0.163415,-0.014634,-0.089113,-0.115661,-0.125650,...,-0.019512,-0.109084,-0.321951,-0.099826,-0.107340,-0.071409,-0.142154,-0.132703,0.077236,0.085494
159,-0.166829,-0.902439,-0.180488,-0.439024,-0.153659,-0.163415,-0.014634,-0.089113,-0.115661,-0.125650,...,-0.019512,-0.063801,-0.036237,-0.042683,0.045041,0.772341,-0.200488,-0.255152,0.355014,0.427599
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-0.366829,0.097561,-0.180488,-0.439024,0.096341,0.336585,-0.014634,0.301557,0.220160,0.249350,...,-0.019512,0.053180,0.249477,0.321603,-0.050197,-0.040159,0.041179,0.112195,-0.061653,-0.072401
184,0.233171,-0.902439,-0.180488,-0.439024,0.096341,-0.163415,-0.014634,-0.042466,-0.035064,-0.033984,...,-0.019512,-0.112858,-0.036237,-0.228397,0.068850,0.803591,-0.217154,-0.132703,0.327236,0.401284
131,0.233171,0.097561,-0.180488,0.560976,-0.153659,-0.163415,-0.014634,-0.077451,0.041056,0.057683,...,-0.019512,0.019218,0.249477,0.093031,0.306945,-0.090159,-0.058821,-0.010254,-0.061653,0.006547
152,0.033171,0.097561,-0.180488,-0.439024,-0.153659,-0.163415,-0.014634,-0.089113,-0.229094,-0.192317,...,-0.019512,-0.131726,-0.321951,-0.199826,-0.107340,-0.071409,-0.175488,-0.132703,0.160569,0.190757
106,0.033171,0.097561,-0.180488,0.560976,-0.153659,0.336585,-0.014634,0.012928,0.066429,0.166016,...,0.147154,0.204123,0.249477,0.071603,0.006945,-0.071409,0.232846,0.030562,-0.172764,-0.151348

In [144]:
y_train.head(15)

135    0.055441
134    0.043774
41    -0.008235
161   -0.122107
159   -0.136257
15     0.434022
64    -0.050437
132   -0.035418
187   -0.093881
174   -0.064016
23    -0.132062
89    -0.193082
31    -0.159419
105    0.159433
133   -0.027474
Name: price, dtype: float64

### Function to calculate cost and Gradient

In [168]:
def gradient_fwd(X,Y,W,b):
    '''
    parameters:
    X:Matrix consisting of features
    Y:Matrix containing actual price 
    W:Weights(that needs to be adjusted)
    b:bias term
    
    returns:
    error: error term(Sum of Square of error is used here.)
    dW:gradient descent for weight matrix
    db:gradient descent for bias term
    
    '''
    y_pred = b + np.dot(X,W.T)
    y_actual = Y.values.reshape(Y.shape[0], 1)
    
    error = np.sum(y_pred-y_actual)**2
    
    dW = -2* np.dot((y_actual - y_pred).T, X)
    
    db = -2*np.sum(y_actual-y_pred)
    
    return error,dW,db
    
# a,b = gradient_fwd(X_train,y_train,np.random.random((1,X_train.shape[1])),0)
# a.shape

### Function to adjust weight

In [183]:
def adjust_wt(X,Y,W,b,n_iter,learning_rate):
    '''
    parameters:
    X:Matrix of Features
    Y:Matrix containing actual price
    W:Weights(to be adjusted)
    b:bias(to be adjusted)
    n_iter: no. of iterations
    
    returns:
    error: error term(Sum of Square of error is used here.)
    W:Adjusted Weight Matrix
    b:Adjusted bias Term
    
    '''
    errors = []

    for i in range(n_iter):
        # Cost and gradient calculation call function propagate
        err,dW,db = gradient_fwd(X, Y,W,b)

        

        # update parameters
        W = W - learning_rate * dW
        b = b - learning_rate * db

        errors.append(err)


    return errors, W,b

### Function that Predicts the value

In [171]:
def calculate(X,W,b):
    '''
    parameters:
    X: Matrix of Features
    B: Weights
    b:bias term
    
    returns:
    predicted_value: The value computed from the parameters
    '''
    predicted_value = b + np.dot(X,W.T)
    return predicted_value

### Actual Model that implements linear regression

In [179]:
def linear_regression(X_train, y_train, X_test, y_test, iter=2000, learning_rate=0.5):
    '''
    parameters:
    X_train: Matrix of features that is used for training(80% of total data of dataset)
    y_train: Matrix that contains the actual price used for model training(80% of total data of dataset)
    X_test: Matrix of features that is used for testing model(20% of total data of dataset)
    y_test: Matrix that contains the actual price used for model testing(20% of total data of dataset)
    
    returns:
    result: A dictionary containing all the information of model
    '''
     # randomly initialize the parameters
    W = np.random.random((1, X_train.shape[1]))
    b = 0
     
    # Gradient descent
    error,weight,bias = adjust_wt(X_train, y_train,W,b, iter, learning_rate)
    
    # Calculate the predicted value
    Y_prediction_test = calculate(X_test,W,b)
    Y_prediction_train = calculate(X_train,W,b)
    
    #actual values
    Y_train = y_train.values.reshape(y_train.shape[0], 1)
    Y_test = y_test.values.reshape(y_test.shape[0], 1)
    
    # Print train/test Errors
    print("train accuracy: {} %".format(100 - np.mean(np.abs(Y_prediction_train - Y_train)) * 100))
    print("test accuracy: {} %".format(100 - np.mean(np.abs(Y_prediction_test - Y_test)) * 100))

    result = {"errors": error,
         "Y_prediction_test": Y_prediction_test,
         "Y_prediction_train": Y_prediction_train,
         "W": W,
         "b": b,
         "learning_rate": learning_rate,
         "num_iterations": iter}

    return result

### Accessing the model

In [235]:
model1 = linear_regression(X_train, y_train, X_test,y_test, iter = 800, learning_rate = 0.0005)

train accuracy: 64.05030724625621 %
test accuracy: 68.25631882545456 %

In [190]:
model1 = linear_regression(X_train, y_train, X_test,y_test, iter = 4500, learning_rate = 0.005)

train accuracy: 49.08035929467558 %
test accuracy: 48.76400640476132 %

In [198]:
model1 = linear_regression(X_train, y_train, X_test,y_test, iter = 500, learning_rate = 0.3)

train accuracy: 53.08836256810248 %
test accuracy: 56.17716012203069 %

C:\Users\pawan\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:12: RuntimeWarning: overflow encountered in double_scalars
  if sys.path[0] == '':
C:\Users\pawan\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:26: RuntimeWarning: invalid value encountered in double_scalars